### ISSUE TITLE
Hi, I want to know where to get Oscar checkpoint

### ISSUE THREAD

**Issue by SZhanZ** [ChenyuHeidiZhang/VL-commonsense#1]
Thank you for your work!
I notice that there are ['pretrained_base/checkpoint-2000000'](https://github.com/ChenyuHeidiZhang/VL-commonsense/blob/main/Oscar/eval_fill_mask.py#L138) in your code, I guess it's the checkpoint of Oscar pretrained model, I want to know how to get it, could u plz offer a download link? Thanks in advance~

**Comment by ChenyuHeidiZhang** [comment]
Here is the pretrained Oscar model checkpoint that I used: https://biglmdiag.blob.core.windows.net/vinvl/model_ckpts/image_captioning/pretrained_base.zip 

Thanks!
