### ISSUE TITLE
Templates for probing

### ISSUE THREAD

**Issue by YueYANG1996** [ChenyuHeidiZhang/VL-commonsense#2]
Hi,

Thanks for sharing this awesome work! I want to know where can I find the 7 templates for each type?

Yue

**Comment by ChenyuHeidiZhang** [comment]
Hi Yue,
Thanks for asking. Here's where the templates are: https://github.com/ChenyuHeidiZhang/VL-commonsense/tree/main/soft-prompts/prompts/vl

Chenyu
