### ISSUE TITLE
Running Oscar

### ISSUE THREAD

**Issue by woojeongjin** [ChenyuHeidiZhang/VL-commonsense#3]
Hi!
I want to run Oscar on your dataset but I got the following error when running "eval_zero_shot.py"

```
Traceback (most recent call last):
  File "probing/eval_zero_shot.py", line 194, in <module>
    test()
  File "probing/eval_zero_shot.py", line 184, in test
    sp_mean, sp_std, acc = run(args, distilled=False)
  File "probing/eval_zero_shot.py", line 49, in run
    model, tokenizer = init_mlm_model(args.model, args.model_size, device)
  File "/home/woojeong2/VL-commonsense/probing/models.py", line 65, in init_mlm_model
    model = BertImgForPreTraining.from_pretrained(dir + "/pytorch_model.bin", config=config)
  File "/home/woojeong2/VL-commonsense/probing/modeling_utils.py", line 801, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/woojeong2/VL-commonsense/probing/modeling_bert.py", line 695, in __init__
    super(BertImgForPreTraining, self).__init__(config)
  File "/home/woojeong2/VL-commonsense/probing/modeling_utils.py", line 686, in __init__
    super(ImgPreTrainedModel, self).__init__(config, *inputs, **kwargs)
  File "/home/woojeong2/miniconda3/envs/vicomte/lib/python3.7/site-packages/pytorch_transformers/modeling_utils.py", line 287, in __init__
    self.__class__.__name__, self.__class__.__name__
ValueError: Parameter config in `BertImgForPreTraining(config)` should be an instance of class `PretrainedConfig`. To create a model from a pretrained model use `model = BertImgForPreTraining.from_pretrained(PRETRAINED_MODEL_NAME)`
```

I downloaded the correct ckpt from the closed issue but I don't know how to solve this error.

Thanks!

**Comment by ChenyuHeidiZhang** [comment]
Do you have a `config.json` and a `pytorch_model.bin` under the specified directory `dir`?

**Comment by woojeongjin** [comment]
Yes I have the `config.json` and `pytorch_model.bin` in the dir. I got the files from oscar ckpt.
The code reads the config file but the error says the config file is not for the `BertImgForPreTraining`

**Comment by ChenyuHeidiZhang** [comment]
I am unable to replicate this error.
If the code reads the config successfully then the config should be `BertConfig`, which is an instance of `PretrainedConfig`, but the error says it is not. May be a library version issue? Can you check against the requirement.txt.

**Comment by woojeongjin** [comment]
I am using transformers 4.0.0 and pytorch_transformers 1.2.0.
Could you check whether the following config is correct? 
It seems there is mismatch between the `BertImgForPreTraining(config)`, `PretrainedConfig`, and the following config.

```
{
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "img_feature_dim": 2054,
  "img_feature_type": "faster_r-cnn",
  "img_layer_norm_eps": 1e-12,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_bert": true,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_contrast_classes": 3,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "pad_token_id": 0,
  "torchscript": false,
  "type_vocab_size": 2,
  "use_img_layernorm": 1,
  "vocab_size": 30522
}
```

**Comment by ChenyuHeidiZhang** [comment]
yes, that is the correct config file.
Are you importing BertConfig from pytorch_transformers or just transformers? You'd be getting an error with the transformers library as an artifact of the Oscar code.

**Comment by woojeongjin** [comment]
I am importing BertConfig from transformers.
I didn't change the code and I used the correct version of transformers hmm...
Actually there was an error on CLIP and VisualBert so I commented out the code for those.
Did you try running this github code?

**Comment by ChenyuHeidiZhang** [comment]
Yes, this GitHub code imports BertConfig from pytorch_transformers, and that should work. For VisualBert you need to upgrade the transformers library.

**Comment by woojeongjin** [comment]
Oh Thanks I edited the code (import part) and I thought I reverted it!
It works now. Thanks for your reply!
